export const equipment = [
  {
    id: 'truck',
    name: '현장 트럭',
    model: 'SITE TRANSPORT',
    type: 'truck',
    color: 0xe87938,
    x: -62,
    z: 17,
    rotation: Math.PI,
    source: '현장 이동용 트럭 · 일반화한 모델',
  },
  {
    id: 'crane',
    name: '크롤러 크레인',
    model: 'CX 1200HD-2',
    type: 'crane',
    color: 0xe8a63d,
    x: -28,
    z: 22,
    rotation: -0.35,
    source: '브로슈어 인쇄 p.10 · 건설용 중장비',
  },
  {
    id: 'cutter',
    name: '트렌치 커터',
    model: 'SC40',
    type: 'cutter',
    color: 0xe3ad34,
    x: 49,
    z: -10,
    rotation: 0,
    source: '브로슈어 인쇄 p.10–13 · 연속벽 장비',
  },
  {
    id: 'grab',
    name: '하이드로 그랩',
    model: 'HSG 5-18L',
    type: 'grab',
    color: 0xcf783c,
    x: -49,
    z: -23,
    rotation: 1.3,
    source: '브로슈어 인쇄 p.11 · 해외 연속벽 장비',
  },
] as const;
export type EquipmentId = (typeof equipment)[number]['id'];
export const zones = [
  { name: '장비 야드', x: -28, z: 26 },
  { name: 'PPS 굴착 구역', x: 5, z: -12 },
  { name: '연속벽 시공 구역', x: 51, z: -15 },
  { name: '슬러리 플랜트', x: -57, z: -44 },
  { name: '자재 적치장', x: 56, z: 40 },
  { name: '현장 사무소', x: -62, z: 43 },
];
